"""room capacity and system prompt

Revision ID: 40efbe33c196
Revises: e5f17351217d
Create Date: 2026-08-25 11:57:17.357964
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '40efbe33c196'
down_revision: Union[str, None] = 'e5f17351217d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('max_players', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('rooms', sa.Column('system_prompt', sa.Text(), nullable=False, server_default=''))
    op.alter_column('rooms', 'max_players', server_default=None)
    op.alter_column('rooms', 'system_prompt', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'system_prompt')
    op.drop_column('rooms', 'max_players')
    # ### end Alembic commands ###