"""add emotion to chat_messages

Revision ID: a4563f91e8b6
Revises: 40efbe33c196
Create Date: 2026-08-25 16:17:20.859649
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4563f91e8b6'
down_revision: Union[str, None] = '40efbe33c196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('emotion', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'emotion')
    # ### end Alembic commands ###