"""add chat message replies

Revision ID: e5f17351217d
Revises: 959095d49d97
Create Date: 2026-08-25 11:03:44.080152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5f17351217d'
down_revision: Union[str, None] = '959095d49d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('reply_to_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_messages', 'chat_messages', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'reply_to_id')
    # ### end Alembic commands ###